<?php

namespace ContainerXetuwNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KmVSFk7Service extends Caas23_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.KmVSFk7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KmVSFk7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'petroRepository' => ['privates', 'Caas23\\Repository\\EnergyPetroRepository', 'getEnergyPetroRepositoryService', true],
        ], [
            'petroRepository' => 'Caas23\\Repository\\EnergyPetroRepository',
        ]);
    }
}
