<?php

namespace ContainerXetuwNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Dt78ZW8Service extends Caas23_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.Dt78ZW8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Dt78ZW8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Caas23\\Controller\\Kmom05Controller::deleteBookById' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'Caas23\\Controller\\Kmom05Controller::libraryPost' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'Caas23\\Controller\\Kmom05Controller::resetLibrary' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'Caas23\\Controller\\Kmom05Controller::showAllBooks' => ['privates', '.service_locator.wn1jA0N', 'get_ServiceLocator_Wn1jA0NService', true],
            'Caas23\\Controller\\Kmom05Controller::showAllBooksAPI' => ['privates', '.service_locator.wn1jA0N', 'get_ServiceLocator_Wn1jA0NService', true],
            'Caas23\\Controller\\Kmom05Controller::showBookById' => ['privates', '.service_locator.wn1jA0N', 'get_ServiceLocator_Wn1jA0NService', true],
            'Caas23\\Controller\\Kmom05Controller::showOneBookAPI' => ['privates', '.service_locator.wn1jA0N', 'get_ServiceLocator_Wn1jA0NService', true],
            'Caas23\\Controller\\Kmom05Controller::updateBookById' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'Caas23\\Controller\\Kmom05Controller::updateBookByIdPost' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'Caas23\\Controller\\Kmom10Controller::energy' => ['privates', '.service_locator.8rsiE3X', 'get_ServiceLocator_8rsiE3XService', true],
            'Caas23\\Controller\\Kmom10Controller::health' => ['privates', '.service_locator.wiWYLaP', 'get_ServiceLocator_WiWYLaPService', true],
            'Caas23\\Controller\\Kmom10ControllerApi::apiEnergyUse' => ['privates', '.service_locator.Eltrax3', 'get_ServiceLocator_Eltrax3Service', true],
            'Caas23\\Controller\\Kmom10ControllerApi::energyApi1' => ['privates', '.service_locator.oLwHXn4', 'get_ServiceLocator_OLwHXn4Service', true],
            'Caas23\\Controller\\Kmom10ControllerApi::energyApi2' => ['privates', '.service_locator.KmVSFk7', 'get_ServiceLocator_KmVSFk7Service', true],
            'Caas23\\Controller\\Kmom10ControllerApi::healthApi1' => ['privates', '.service_locator.9XURTj_', 'get_ServiceLocator_9XURTjService', true],
            'Caas23\\Controller\\Kmom10ControllerApi::healthApi2' => ['privates', '.service_locator.cpaVhCo', 'get_ServiceLocator_CpaVhCoService', true],
            'Caas23\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'Caas23\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'Caas23\\Controller\\Kmom05Controller:deleteBookById' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'Caas23\\Controller\\Kmom05Controller:libraryPost' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'Caas23\\Controller\\Kmom05Controller:resetLibrary' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'Caas23\\Controller\\Kmom05Controller:showAllBooks' => ['privates', '.service_locator.wn1jA0N', 'get_ServiceLocator_Wn1jA0NService', true],
            'Caas23\\Controller\\Kmom05Controller:showAllBooksAPI' => ['privates', '.service_locator.wn1jA0N', 'get_ServiceLocator_Wn1jA0NService', true],
            'Caas23\\Controller\\Kmom05Controller:showBookById' => ['privates', '.service_locator.wn1jA0N', 'get_ServiceLocator_Wn1jA0NService', true],
            'Caas23\\Controller\\Kmom05Controller:showOneBookAPI' => ['privates', '.service_locator.wn1jA0N', 'get_ServiceLocator_Wn1jA0NService', true],
            'Caas23\\Controller\\Kmom05Controller:updateBookById' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'Caas23\\Controller\\Kmom05Controller:updateBookByIdPost' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'Caas23\\Controller\\Kmom10Controller:energy' => ['privates', '.service_locator.8rsiE3X', 'get_ServiceLocator_8rsiE3XService', true],
            'Caas23\\Controller\\Kmom10Controller:health' => ['privates', '.service_locator.wiWYLaP', 'get_ServiceLocator_WiWYLaPService', true],
            'Caas23\\Controller\\Kmom10ControllerApi:apiEnergyUse' => ['privates', '.service_locator.Eltrax3', 'get_ServiceLocator_Eltrax3Service', true],
            'Caas23\\Controller\\Kmom10ControllerApi:energyApi1' => ['privates', '.service_locator.oLwHXn4', 'get_ServiceLocator_OLwHXn4Service', true],
            'Caas23\\Controller\\Kmom10ControllerApi:energyApi2' => ['privates', '.service_locator.KmVSFk7', 'get_ServiceLocator_KmVSFk7Service', true],
            'Caas23\\Controller\\Kmom10ControllerApi:healthApi1' => ['privates', '.service_locator.9XURTj_', 'get_ServiceLocator_9XURTjService', true],
            'Caas23\\Controller\\Kmom10ControllerApi:healthApi2' => ['privates', '.service_locator.cpaVhCo', 'get_ServiceLocator_CpaVhCoService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'Caas23\\Controller\\Kmom05Controller::deleteBookById' => '?',
            'Caas23\\Controller\\Kmom05Controller::libraryPost' => '?',
            'Caas23\\Controller\\Kmom05Controller::resetLibrary' => '?',
            'Caas23\\Controller\\Kmom05Controller::showAllBooks' => '?',
            'Caas23\\Controller\\Kmom05Controller::showAllBooksAPI' => '?',
            'Caas23\\Controller\\Kmom05Controller::showBookById' => '?',
            'Caas23\\Controller\\Kmom05Controller::showOneBookAPI' => '?',
            'Caas23\\Controller\\Kmom05Controller::updateBookById' => '?',
            'Caas23\\Controller\\Kmom05Controller::updateBookByIdPost' => '?',
            'Caas23\\Controller\\Kmom10Controller::energy' => '?',
            'Caas23\\Controller\\Kmom10Controller::health' => '?',
            'Caas23\\Controller\\Kmom10ControllerApi::apiEnergyUse' => '?',
            'Caas23\\Controller\\Kmom10ControllerApi::energyApi1' => '?',
            'Caas23\\Controller\\Kmom10ControllerApi::energyApi2' => '?',
            'Caas23\\Controller\\Kmom10ControllerApi::healthApi1' => '?',
            'Caas23\\Controller\\Kmom10ControllerApi::healthApi2' => '?',
            'Caas23\\Kernel::loadRoutes' => '?',
            'Caas23\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'Caas23\\Controller\\Kmom05Controller:deleteBookById' => '?',
            'Caas23\\Controller\\Kmom05Controller:libraryPost' => '?',
            'Caas23\\Controller\\Kmom05Controller:resetLibrary' => '?',
            'Caas23\\Controller\\Kmom05Controller:showAllBooks' => '?',
            'Caas23\\Controller\\Kmom05Controller:showAllBooksAPI' => '?',
            'Caas23\\Controller\\Kmom05Controller:showBookById' => '?',
            'Caas23\\Controller\\Kmom05Controller:showOneBookAPI' => '?',
            'Caas23\\Controller\\Kmom05Controller:updateBookById' => '?',
            'Caas23\\Controller\\Kmom05Controller:updateBookByIdPost' => '?',
            'Caas23\\Controller\\Kmom10Controller:energy' => '?',
            'Caas23\\Controller\\Kmom10Controller:health' => '?',
            'Caas23\\Controller\\Kmom10ControllerApi:apiEnergyUse' => '?',
            'Caas23\\Controller\\Kmom10ControllerApi:energyApi1' => '?',
            'Caas23\\Controller\\Kmom10ControllerApi:energyApi2' => '?',
            'Caas23\\Controller\\Kmom10ControllerApi:healthApi1' => '?',
            'Caas23\\Controller\\Kmom10ControllerApi:healthApi2' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
