<?php

namespace ContainerXetuwNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8rsiE3XService extends Caas23_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.8rsiE3X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8rsiE3X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chartBuilder' => ['privates', 'chartjs.builder', 'getChartjs_BuilderService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'petroRepository' => ['privates', 'Caas23\\Repository\\EnergyPetroRepository', 'getEnergyPetroRepositoryService', true],
            'supplyRepository' => ['privates', 'Caas23\\Repository\\EnergySupplyRepository', 'getEnergySupplyRepositoryService', true],
            'useRepository' => ['privates', 'Caas23\\Repository\\EnergyUseRepository', 'getEnergyUseRepositoryService', true],
        ], [
            'chartBuilder' => '?',
            'doctrine' => '?',
            'petroRepository' => 'Caas23\\Repository\\EnergyPetroRepository',
            'supplyRepository' => 'Caas23\\Repository\\EnergySupplyRepository',
            'useRepository' => 'Caas23\\Repository\\EnergyUseRepository',
        ]);
    }
}
