<?php

namespace ContainerXetuwNG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wn1jA0NService extends Caas23_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.wn1jA0N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wn1jA0N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'libraryRepository' => ['privates', 'Caas23\\Repository\\LibraryRepository', 'getLibraryRepositoryService', true],
        ], [
            'libraryRepository' => 'Caas23\\Repository\\LibraryRepository',
        ]);
    }
}
