<?php

namespace ContainerPAGz1mN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WiWYLaPService extends Caas23_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wiWYLaP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wiWYLaP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chartBuilder' => ['privates', 'chartjs.builder', 'getChartjs_BuilderService', true],
            'covidRepository' => ['privates', 'Caas23\\Repository\\DeceasedCovidRepository', 'getDeceasedCovidRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'generalRepository' => ['privates', 'Caas23\\Repository\\DeceasedGeneralRepository', 'getDeceasedGeneralRepositoryService', true],
        ], [
            'chartBuilder' => '?',
            'covidRepository' => 'Caas23\\Repository\\DeceasedCovidRepository',
            'doctrine' => '?',
            'generalRepository' => 'Caas23\\Repository\\DeceasedGeneralRepository',
        ]);
    }
}
