<?php

namespace ContainerPAGz1mN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CpaVhCoService extends Caas23_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cpaVhCo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cpaVhCo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'covidRepository' => ['privates', 'Caas23\\Repository\\DeceasedCovidRepository', 'getDeceasedCovidRepositoryService', true],
        ], [
            'covidRepository' => 'Caas23\\Repository\\DeceasedCovidRepository',
        ]);
    }
}
