<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXetuwNG\Caas23_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXetuwNG/Caas23_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXetuwNG.legacy');

    return;
}

if (!\class_exists(Caas23_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXetuwNG\Caas23_KernelTestDebugContainer::class, Caas23_KernelTestDebugContainer::class, false);
}

return new \ContainerXetuwNG\Caas23_KernelTestDebugContainer([
    'container.build_hash' => 'XetuwNG',
    'container.build_id' => 'afc9203f',
    'container.build_time' => 1717408114,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXetuwNG');
