<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPAGz1mN\Caas23_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPAGz1mN/Caas23_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPAGz1mN.legacy');

    return;
}

if (!\class_exists(Caas23_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPAGz1mN\Caas23_KernelDevDebugContainer::class, Caas23_KernelDevDebugContainer::class, false);
}

return new \ContainerPAGz1mN\Caas23_KernelDevDebugContainer([
    'container.build_hash' => 'PAGz1mN',
    'container.build_id' => 'eea7445f',
    'container.build_time' => 1717416761,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPAGz1mN');
